### ISSUE TITLE
How to copy files while preserving compression attributes?

### ISSUE THREAD

**Issue by nil-ref** [LTRData/strarc#1]
First, I compressed the file using the following command:
`compact /c /s /a /i /exe:lzx "E:\1\log.txt"`

Then, I used the following command to copy:
`strarc.exe -cj -m:f -d:1 | strarc.exe -xod:2`

But the compression of file "E:\2\log.txt" is lost.

**Comment by Olof-Lagerkvist** [comment]
Just tried this a few times now and it seems to work here. Not really sure why it would not work in your case. Could you try with verbose mode for the extraction side and see if we can get any clues? (Add `-v` to extraction process.)

**Comment by Olof-Lagerkvist** [comment]
Sorry! I missed that you used the `/exe` switch to compress! That is a completely different thing and is not supported in this way. It is a different kind of compression method that does not use compressed attributes but rather a separate compressed data stream attached to the file. That data stream is not accessible as raw bytes. When you copy, modify or in any other way do anything to the file except reading from it or execute it, the compression is lost.
